version: "3.9"

services:
  backend:
    image: purvatarale/courses-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    image: purvatarale/courses-frontend:latest
    environment:
      BASE_URL: "http://backend:8000"
    ports:
      - "3000:3000"
