# Generated by Django 5.1 on 2024-08-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='instance_id',
        ),
    ]
